# brownie-config.yaml

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
  - smartcontractkit/chainlink-brownie-contracts@1.2.0

compiler:
  solc:
    version: 0.8.17  # Ensure this matches your Solidity pragma version
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'

networks:
  development:
    host: http://127.0.0.1
    port: 8545
    network_id: 1337
    eth_gbp_price_feed: "0x0000000000000000000000000000000000000000"
    verify: False


#dotenv: .env  # Include this line if you're using environment variables
