dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0  # or the latest version
  - smartcontractkit/chainlink-brownie-contracts@1.1.1  # or the latest version

compiler:
  solc:
    version: 0.8.17  # Ensure this matches your Solidity pragma version
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'  # Update if using a different version

networks:
  development:
    host: http://127.0.0.1
    port: 7545  # Update to 7545 if using the default Ganache settings
    network_id: 5777  # Update to 5777 if using the default Ganache settings
    eth_gbp_price_feed: "0x0000000000000000000000000000000000000000"  # Update with actual price feed address when available
    verify: False

filebase:
  api_key: D2E36D112C666892F8D3


#dotenv: .env  # Uncomment if you're using environment variables
