name: Batterypassport_ev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
      # Add any other environment variables your project requires
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: true  # Ensures the working directory is clean before checkout

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install eth-brownie
          pip install -r requirements.txt

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Ganache CLI
        run: npm install -g ganache

      - name: Run Brownie Tests
        env:
          WEB3_PROVIDER_URI: http://127.0.0.1:8545
        run: |
          nohup ganache-cli > /dev/null &
          sleep 5
          brownie test
